spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS:org.h2.Driver}
    url: ${DB_URL:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASS:sa}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
